include(${CMAKE_CURRENT_LIST_DIR}/cmake/utility.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cmake/version.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cmake/targets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cmake/groups.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cmake/include.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cmake/export.cmake)